//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaNoelOrtiz
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    
    public partial class Persona
    {
       
        public int Id { get; set; }
        public string Nombre { get; set; }


        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        
        public DateTime FechaDeNacimiento { get; set; }
    }
}
